name: Convert Marpit Presentations to HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install Marp CLI
    - name: Install Marp CLI
      run: npm install -g @marp-team/marp-cli

    # Step 4: Convert Markdown files to HTML
    - name: Convert Markdown to HTML
      run: |
        mkdir -p converted
        for file in $(find presentation -name '*.md'); do
          marp "$file" --html --output "converted/$(basename "${file%.md}.html")"
        done

    # Step 5: Commit and push the converted HTML files
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        cp -r converted/* presentation/
        git add presentation/*.html
        git commit -m "Convert Marpit presentations to HTML [skip ci]" || echo "No changes to commit"
        git push